# Generated by: Tobias Mueller
# Generated on: 13.08.2018

@{
    RootModule        = 'MyFunctions.psm1'
    ModuleVersion     = '0.5.0'
    GUID              = '9741e3a0-2346-48db-9989-8b6206b72c11'
    Author            = 'Tobias Mueller'
    CompanyName       = 'Stadt Schriesheim'
    Copyright         = '(c) Tobias Mueller. All rights reserved.'
    Description       = 'Modul mit Cmdlets die vom Autor für den täglischen Gebrauch genutzt werden.'
    FunctionsToExport = @('Test-Service',
        'Invoke-Ping',
        'Search-ADUser',
        'Clear-AllEventLog'
        'Get-ServiceLogonAccount'
        'Get-DHCPRecentLease'
        'Save-PSFConfig'
        'Get-ImcSwitchPort'
        'Get-IPMAC'
        'Update-PSFConfig',
        'New-EncryptedZipUsing7Zip'
        'Publish-PhoneList'
        'Get-PhoneList'
        'Export-ADUserToExcel'
        'Import-ADUserFromExcel')
    CmdletsToExport   = ''
    VariablesToExport = ''
    AliasesToExport   = @('sAD')
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

